omkarkhatavkar/github-action-test-repo

- README.md
Reverts omkarkhatavkar/github-action-test-repo#28
> Revert "test pr for testing github actions"

- README.md
> updated the README File

- README.md
> new commit 1

- README.md
> adding new actions

- README.md
> testing the output yaml

- README.md
> testing the output

- README.md
> added new pr

- README.md
Reverts omkarkhatavkar/github-action-test-repo#60
> Revert "Revert "Revert "added new pr"""

- README.md
Reverts omkarkhatavkar/github-action-test-repo#62
> Revert "Revert "Revert "Revert "added new pr""""

- README.md
testing PRT comment in the cherrypick PR's
> testing PRT comment in the cherrypick PR's

- README.md
Reverts omkarkhatavkar/github-action-test-repo#68
> Revert "testing PRT comment in the cherrypick PR's"

- README.md
test notification author and issue url
> test notification author and issue url

- test
> added auto merge and test auto merge

- test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/90
test auto merge
> [6.11.z] added auto merge and test auto merge

- test
Reverts omkarkhatavkar/github-action-test-repo#93
> Revert "Revert "added automerge and test automerge""

- test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/94
Reverts omkarkhatavkar/github-action-test-repo#93
> [6.11.z] Revert "Revert "added automerge and test automerge""

- test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/96
null
> [6.11.z] testing auto merge

- test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/98
null
> [6.11.z] testing automerge pr 2

- test
> testing automerge pr 23

- .github/workflows/test
> added support for the auto merge

- .github/workflows/test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/103
test auto merge
> [6.11.z] added support for the auto merge

- test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/105
added the auto merge full fledge
> [6.11.z] added the auto merge full fledge

- .github/workflows/test
> remove unwanted test file

- .github/workflows/test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/107
remove unwanted test file
> [6.11.z] remove unwanted test file

- .github/workflows/test
Reverts omkarkhatavkar/github-action-test-repo#107
> Revert "remove unwanted test file"

- test
testing the label in child PR's
> testing the label in child PR's

- test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/112
testing the label in child PR's
> [6.11.z] testing the label in child PR's

- test
Reverts omkarkhatavkar/github-action-test-repo#112
> Revert "testing the label in child PR's"

- test
Reverts omkarkhatavkar/github-action-test-repo#115
> Revert "Revert "testing the label in child PR's""

- test
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/118
Reverts omkarkhatavkar/github-action-test-repo#115
> [6.11.z] Revert "Revert "testing the label in child PR's""

- README.md
> testing the sleep 5 min

- README.md
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/120
testing the sleep 5 min
> [6.11.z] testing the sleep 5 min

- README.md
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/122
Reverts omkarkhatavkar/github-action-test-repo#120
> [6.11.z] Revert "testing the sleep 5 min"

- README.md
Reverts omkarkhatavkar/github-action-test-repo#122
> Revert "Revert "testing the sleep 5 min""

- README.md
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/124
Reverts omkarkhatavkar/github-action-test-repo#122
> [6.11.z] Revert "Revert "testing the sleep 5 min""

- README.md
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/126
Removed extra lines.
> [6.11.z] Update README.md

- README.md
Cherrypick of PR: https://github.com/omkarkhatavkar/github-action-test-repo/pull/128
Reverts omkarkhatavkar/github-action-test-repo#126
> [6.11.z] Revert "Update README.md"
